### ISSUE TITLE
',' expected.

### ISSUE THREAD

**Issue by jfr8036** [JacobFischer/ts-typed-events#1]
I'm getting  the error:
ERROR in [at-loader] ./node_modules/ts-typed-events/js/src/event.d.ts:7:42
    TS1005: ',' expected.

ERROR in [at-loader] ./node_modules/ts-typed-events/js/src/event.d.ts:4:26
    TS2314: Generic type 'Event<T, undefined>' requires 2 type argument(s).

the issue is with the line:
`export class Event<T extends any = undefined> {`

**Comment by JacobFischer** [comment]
Sorry, didn't see this till now.

By chance what version of TypeScript are you running? Some quicky googling on my part shows that older versions say this when they see default generic types (`T = undefined`), before that was added.

**Comment by JacobFischer** [comment]
As of v2.0.0 TypeScript >= 3.0.0 is required so this issue should not drop up.
