### ISSUE TITLE
Prefer v2 model

### ISSUE THREAD

**Issue by isometriq** [JacobFischer/ts-typed-events#18]
Maybe a personal taste, I find the v2 model more expressive and easier to read.

**Comment by JacobFischer** [comment]
I'm open to keeping the v2 model essentially untouched for v3.

This was a topic I discussed with some other developers using this library. We essentially wanted to add the functionality added/described in #14; events that don't expose their emit functions.

I had not considered it at the time, but keeping the v2 model for naming would make upgrade paths easier for developers using this module. Essentially they could keep using `Event` like normal, or refactor their code to use these new events without `event.emit` when they see fit.

`SealedEvent` was the class named used for those events in that PR. I also played with `PrivateEvent` and `BaseEvent`, but eventually gave it the name `Event` and renamed the v2 `Event` class to `PublicEvent` to better describe its difference.

Do you, or anyone else that agrees, have a better naming model? I'm open to ideas.

**Comment by isometriq** [comment]
Thanks, I will think about it

**Comment by JacobFischer** [comment]
I've issued a new pre-release in v3.0.0-rc.5 with an updated model that I think should address this concern.

The main name model changes are:
- `Event` from v2 is the same as in v3 now.
- `SealedEvent` as originally proposed in #14 is now the name for events without an `.emit` function.
- Both of these event classes inherit from a new `BaseEvent` abstract class.
- `createEmitter()` returns an emitter for a `SealedEvent`
- `createEventEmitter()` return an emitter for a "normal" `Event`.

This way users who like the v2 model can continue doing so with no code changes required, and those that want to de-couple their event registering and emitting logic can do so going forward.

**Comment by JacobFischer** [comment]
The v2 model has been preserved with the above mentioned changes.

For those of you upgrading from v2. Your `new Event<T>()` code should not require any changes at all.

Only `events()` will require reworking as it was removed. See #8 for more information.
