### ISSUE TITLE
Issue with "engines" option

### ISSUE THREAD

**Issue by cypherix93** [JacobFischer/ts-typed-events#2]
#### Problem

Hi, I am running Node v8.9.1 with yarn v1.3.2 and it's complaining about the accuracy of engines in the package's metadata:

```
error ts-typed-events@1.0.1: The engine "node" is incompatible with this module. Expected version "8.5.0".
```

#### Suggested Solution

The `engines` option in `package.json` should probably be a range.

It is currently: 
```json
"engines": {
    "node": "8.5.0"
}
```
Should probably be something like:
```json
"engines": {
    "node": ">= 8.5.0"
}
```

**Comment by JacobFischer** [comment]
Thanks, that's an excellent suggestion. I'll try to update this and #1 for a new bug fix release soon.

**Comment by cypherix93** [comment]
PR made.
