### ISSUE TITLE
Warning with sourceMap

### ISSUE THREAD

**Issue by konstantin24121** [JacobFischer/ts-typed-events#6]
Source map files has links to non-exist files

events.js.map

```js
"sources":["../../src/events.ts"]
```

If you want supply you package with sourceMaps you should public src folder too

**Comment by JacobFischer** [comment]
Sorry, I did not notice this issue until earlier this week, and spent my past few evening doing maintenance on the package. Fixing this issue and improving the package.

Source maps should now be fixed in the new v2.0.0 release.

Thanks for your support!
