### ISSUE TITLE
Inherited Class and calling super.events

### ISSUE THREAD

**Issue by andreasmwenzel** [JacobFischer/ts-typed-events#8]
**Problem**
The example in the README for events on inherited classes doesn't work as written. When running it, I get the error:
```
pug.events.called.once(console.log);
                  ^

TypeError: Cannot read property 'once' of undefined
```

Inspecting `pug` showed that `snort` was the only event on `pug`.
This seems to have to do with calling `super.events` in the inherited `Pug` class.

A simple example to prove this:
```
class A {
  hi:string = "hello";
}

class B extends A{
  hi:string = super.hi;
}

var b = new B();
console.log(b.hi)
```
returns `undefined`.

**Possible solution**
I was able to work around this using getters for the events:
```
import { Event, events} from "ts-typed-events";

class Dog {
  protected _events = events({
      barked: new Event(),
      called: new Event<string>(),
      didSomethingComplex: new Event<{a: string, b: number, c: boolean[]}>()
  });
  public callIt(name: string): void {
    this._events.called.emit(name);
  }
  get events(){
    return this._events;
  }
};
class Pug extends Dog {
  protected _events = events.concat(super.events,({
    snort: new Event()
  }))
  get events(){
    return this._events;
  }
  public makeSnort(): void {
    this._events.snort.emit();
  }
};

const pug = new Pug();

pug.events.called.once(console.log);
pug.callIt("good boy"); // this still works from the super's events!

pug.events.snort.on(() => {
    console.log("this pug snorted, cute little guy");
});
pug.makeSnort();
console.log(pug.events)

const groupA = events({
  alpha: new Event(),
  beta: new Event(),
});

const groupB = events({
  delta: new Event(),
  gamma: new Event(),
});

const combined = events.concat(groupA, groupB);
console.log(combined);
```

**Comment by JacobFischer** [comment]
Thanks for reporting this issue. I will try to take a look at it. I have some possible solutions in mind similar to the one you sketched out, if what I think is happening.

**Comment by andreasmwenzel** [comment]
Great. Let me know if you come up with something more elegant. I'm not a huge fan of relying on an underscored attribute.

**Comment by andreasmwenzel** [comment]
it also works like this
```
class Dog {
  public readonly events = events({
      barked: new Event(),
      called: new Event<string>(),
      didSomethingComplex: new Event<{a: string, b: number, c: boolean[]}>()
  });
  public callIt(name: string): void {
    this.events.called.emit(name);
  }
};
class Pug extends Dog {
  public readonly events:any = events.concat(this.events,({
    snort: new Event()
  }))
  public makeSnort(): void {
    this.events.snort.emit();
  }
};
```

using `this.events` instead of `super.events`, but that loses the type information having to make `events:any`

**Comment by JacobFischer** [comment]
So yes there's a problem here. We can boil it down to this example:

```ts
import { events, Event } from "ts-typed-events";

class Dog {
    public readonly events = events({
        barked: new Event(),
    });
}

class Pug extends Dog {
    public readonly events = events.concat(super.events, {
        snort: new Event(),
    });
}

const pug = new Pug();
```

`super.events` does not work in the example in the README. So at the very least I need to fix that. So as you pointed out change it to `this.events, ...`, but then we get a new error:
```
error TS7022: 'events' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

     public readonly events = events.concat(this.events, {
```

So there's no run-time problem with this approach. When the inner `this.events` is invoked it will return the super's version of events, then `event.concat` will combine the two so it will all be fine at runtime. TypeScript is just mad at the usage of `this`. And seeing as this module is very TypeScript focused, that is a problem.

As a work around, I got this working:

```ts

const getPugEvents = (dog: Dog) => events.concat(dog.events, {
  snorted: new Event()
});

class Pug extends Dog {
    events = getPugEvents(this);
}
```

This approach is... less than ideal. We are basically bypassing the TypeScript error by passing this out of context for it to complain. So I need to appease TypeScript some other way.

I'm playing with this, but it seems like a TS error. I can actually simplify the example down to remove this module from the problem:
```ts
class Dog {
    events = {
        barked: true,
    };
}

class Pug extends Dog {
    events = {
        ...this.events, // same error here, but we can see it should spread { barked: true }
        snorted: true,
    }
}
```

I'm browsing through a bunch of related errors in the [TypeScript repo](https://github.com/microsoft/TypeScript/issues/). So maybe there is a proper solution to this, or I'll need to make a convenience function similar to `getPugEvents` that can side step TS.

**Comment by JacobFischer** [comment]
So to resolve this issue. I think simply what I will do is remove that example to not advertise `events.concat` in an erroneous usage.

With that being said, I think the better way to restructure this example would have been:
```js
class Dog {
    eventBark = new Event();
}

class Pug extends Dog {
    eventSnort = new Event();
}
```

This way we can leverage class inheritance correctly without this module needing to expose any utility functions.

However, if you really want a `.events` container, this would be another decent option. This was the most elegant I could come up with after discussing with some peers:
```js
class DogEvents {
    barked = true;
}

class PugEvents extends DogEvents {
    snorted = true;
}

class Dog {
    events = new DogEvents();
}

class Pug extends Dog {
    events = new PugEvents();
}
```

Or this option:
```js
class Dog {
    protected getEvents() {
        return {
            barked: new Event(),
        }
    }

    public events = this.getEvents();
}

class Pug extends Dog {
    protected getEvents() {
        return {
            ...super.getEvents(),
            snorted: new Event(),
        }
    }
}
```

So to that end in the next major release I'll probably remove `events.concat`, as it really serves no purpose anymore. But I don't see a good reason to force a breaking change like that yet. I'll wait for a better breaking change to add it to.

**Comment by JacobFischer** [comment]
In addition to the previously mentioned alternatives, the new `createEmitter` model allows for you to create events like this and inherit them as in the above examples

```ts
class Dog {
  private timesBarked = 0;
  // NOTE: the emitter is private here, and the event is public.
  // This allows the class to completely control when it emits.
  private emitBarked = createEmitter();

  public barked = this.emitBarked.event;

  public bark() {
    this.timesBarked += 1;
    this.emitBarked();
  }
}

class Pug extends Dog {
  private emitSnorted = createEmitter();
  public snorted = this.emitSnorted.event;
  
  public bark() {
    super.bark();
    this.emitSnorted();
  }
}

const pug = new Pug();
pug.barked.on(() => console.log('The pug barked!'));
pug.snorted.on(() => console.log('The pug snorted!!!'));

pug.bark(); // prints: `The pug barked!`, and then: `The pug snorted!!!`
```

I hope this helps anyone upgrading from v2 -> v3.
